### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [neonwatty/meme_search#7]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by neonwatty** [comment]
thanks!  added!

went with Apache 2.0 after discussions with some of a few of the model owners / streamlit (they all use apache 2.0, so in that spirit i think it makes sense).
