### ISSUE TITLE
Enhancement Docker - Use Supercronic to automatically run create.py

### ISSUE THREAD

**Issue by thijsvanloef** [neonwatty/meme_search#8]
Indexing currently requires the user to run the following command manually:

```bash
docker exec meme_search python meme_search/utilities/create.py
```

If supercronic would be installed, you would be able to use a [cron expression](https://crontab.guru/) to run it at a set interval.

Let me know if this is something you want me to include, I can open a PR :)

**Comment by neonwatty** [comment]
great idea!  

a few thoughts:

1.  at present the entire directory is indexed with this command 
2.  in terms of design - should we cron or have another process / container monitor the index directory for additions / subtractions?

not sure at the moment on 2, but i need to crank out 1 in any case before proceeding in either direction.  i'll be able to do that tonight.

what do you think about 2?

**Comment by thijsvanloef** [comment]
1. I noticed that it indexed the entire input directory while testing the cron functionality, that does complicate it somewhat.
2. I explored 2 options:
    1. cron
    2. inotifywait

Cron will allow you to define a cron shedule and opens the ability to add more cron tasks in the future.
inotifywait checks for actual changes to the directory before running the create.py,l saving resources, and is probably the more user friendly option.

During testing I would much prefer the inotifywait for this specific process.

**Comment by neonwatty** [comment]
All right!

Just pushed these changes (among others) to address 1:

A new "refresh index" button to update the index when images are added or removed from the data/input image directory, affecting only the newly added or removed images.  See [the gif in the updated README.md](https://github.com/neonwatty/meme_search?tab=readme-ov-file#index-your-own-memes).

Pressing this new button just calls the same command

```sh
python meme_search/utilities/create.py
```

but **now** this command doesn't completely re-create the index, but only 

- adds any new images added to `data/input` to the index
- removes any removed images from the index

This gives us something in the direction of 2 for now as well - as you can now manually refresh your index!
